---
layout: cv
title: Jada Bower's CV
---
# Jada Bower
Computer Scientist and Mathematician.

<div id="webaddress">
<a href="mailto:jadabower@gmail.com">jadabower@gmail.com</a>
| <a href="https://www.linkedin.com/in/jada-bower/">Linkedin</a>
</div>


## Currently

Majoring in Computer Science with a Minor in Mathematics at Brigham Young University-Idaho. I am in my junior year and will graduate at the end of the year. 


### Specialized in

Full-stack development, Calculus, Machine Learning.


## Education

`2022-present`
__Brigham Young University-Idaho__, Rexburg


## Occupation

`2024`
__Retail Architects__, South Carolina

- Created full Vue.js mini-applications
- Formatted documents/customer receipts with HTML and CSS
- Used Google Cloud Run Functions with API calls to create an automated messaging system between GitHub and Freshdesk

`2024`
__Observatory Operator__, Brigham Young University-Idaho

- Operated Celestron telescope and observaory dome
- Provided interesting space facts for guests

`2024`
__Programming with Classes TA__, Brigham Young University-Idaho

- Graded assignments
- Helped students one-on-one to understand the fundamentals of Object-Oriented Programming

`2023`
__Electrical Engineering TA__, Brigham Young University-Idaho

- Graded assignments
- Helped students on in-class lab assignments


<!-- ### Footer

Last updated: May 2013 -->